name: zaccount
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hugeicons: ^0.0.7
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  path_provider:
  sqflite:
  flutter_multi_formatter: ^2.13.0
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  go_router: ^14.2.9
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  flutter_screenutil: ^5.9.3
  uuid: ^4.5.1
  equatable: ^2.0.5
  path: ^1.9.0
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.0+3
  flutter_sticky_header: ^0.6.5
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_ui_auth: ^1.16.0
  firebase_storage: ^12.3.3
  pdf: ^3.11.1
  flutter_expandable_fab: ^2.3.0
  shared_preferences: ^2.3.2
  flutter_gif: ^0.0.4
  http: ^1.2.2
  printing: ^5.13.4
  screenshot: ^3.0.0
  mailer: ^6.2.0
  google_sign_in: ^6.2.2
  flutter_email_sender: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
