const districts = [
  {"district": "Arusha City", "region": "Arusha"},
  {"district": "Arumeru", "region": "Arusha"},
  {"district": "Karatu", "region": "Arusha"},
  {"district": "Longido", "region": "Arusha"},
  {"district": "Monduli", "region": "Arusha"},
  {"district": "Ngorongoro", "region": "Arusha"},
  {"district": "Ilala", "region": "Dar es Salaam"},
  {"district": "Kinondoni", "region": "Dar es Salaam"},
  {"district": "Temeke", "region": "Dar es Salaam"},
  {"district": "Ubungo", "region": "Dar es Salaam"},
  {"district": "Kigamboni", "region": "Dar es Salaam"},
  {"district": "Bahi", "region": "Dodoma"},
  {"district": "Chamwino", "region": "Dodoma"},
  {"district": "Chemba", "region": "Dodoma"},
  {"district": "Dodoma City", "region": "Dodoma"},
  {"district": "Kondoa", "region": "Dodoma"},
  {"district": "Kongwa", "region": "Dodoma"},
  {"district": "Mpwapwa", "region": "Dodoma"},
  {"district": "Bukombe", "region": "Geita"},
  {"district": "Chato", "region": "Geita"},
  {"district": "Geita Town", "region": "Geita"},
  {"district": "Mbogwe", "region": "Geita"},
  {"district": "Nyang'hwale", "region": "Geita"},
  {"district": "Iringa Municipal", "region": "Iringa"},
  {"district": "Iringa Rural", "region": "Iringa"},
  {"district": "Kilolo", "region": "Iringa"},
  {"district": "Mufindi", "region": "Iringa"},
  {"district": "Biharamulo", "region": "Kagera"},
  {"district": "Bukoba Municipal", "region": "Kagera"},
  {"district": "Bukoba Rural", "region": "Kagera"},
  {"district": "Karagwe", "region": "Kagera"},
  {"district": "Kyerwa", "region": "Kagera"},
  {"district": "Misenyi", "region": "Kagera"},
  {"district": "Muleba", "region": "Kagera"},
  {"district": "Ngara", "region": "Kagera"},
  {"district": "Mlele", "region": "Katavi"},
  {"district": "Mpanda Town", "region": "Katavi"},
  {"district": "Mpanda Rural", "region": "Katavi"},
  {"district": "Buhigwe", "region": "Kigoma"},
  {"district": "Kakonko", "region": "Kigoma"},
  {"district": "Kasulu Town", "region": "Kigoma"},
  {"district": "Kasulu Rural", "region": "Kigoma"},
  {"district": "Kibondo", "region": "Kigoma"},
  {"district": "Kigoma Town", "region": "Kigoma"},
  {"district": "Kigoma Rural", "region": "Kigoma"},
  {"district": "Uvinza", "region": "Kigoma"},
  {"district": "Hai", "region": "Kilimanjaro"},
  {"district": "Moshi Municipal", "region": "Kilimanjaro"},
  {"district": "Moshi Rural", "region": "Kilimanjaro"},
  {"district": "Mwanga", "region": "Kilimanjaro"},
  {"district": "Rombo", "region": "Kilimanjaro"},
  {"district": "Same", "region": "Kilimanjaro"},
  {"district": "Siha", "region": "Kilimanjaro"},
  {"district": "Kilwa", "region": "Lindi"},
  {"district": "Lindi Municipal", "region": "Lindi"},
  {"district": "Lindi Rural", "region": "Lindi"},
  {"district": "Liwale", "region": "Lindi"},
  {"district": "Nachingwea", "region": "Lindi"},
  {"district": "Ruangwa", "region": "Lindi"},
  {"district": "Babati Town", "region": "Manyara"},
  {"district": "Babati Rural", "region": "Manyara"},
  {"district": "Hanang'", "region": "Manyara"},
  {"district": "Kiteto", "region": "Manyara"},
  {"district": "Mbulu", "region": "Manyara"},
  {"district": "Simanjiro", "region": "Manyara"},
  {"district": "Bunda", "region": "Mara"},
  {"district": "Butiama", "region": "Mara"},
  {"district": "Musoma Municipal", "region": "Mara"},
  {"district": "Musoma Rural", "region": "Mara"},
  {"district": "Rorya", "region": "Mara"},
  {"district": "Serengeti", "region": "Mara"},
  {"district": "Tarime", "region": "Mara"},
  {"district": "Busokelo", "region": "Mbeya"},
  {"district": "Chunya", "region": "Mbeya"},
  {"district": "Kyela", "region": "Mbeya"},
  {"district": "Mbarali", "region": "Mbeya"},
  {"district": "Mbeya City", "region": "Mbeya"},
  {"district": "Mbeya Rural", "region": "Mbeya"},
  {"district": "Rungwe", "region": "Mbeya"},
  {"district": "Gairo", "region": "Morogoro"},
  {"district": "Kilombero", "region": "Morogoro"},
  {"district": "Kilosa", "region": "Morogoro"},
  {"district": "Morogoro Municipal", "region": "Morogoro"},
  {"district": "Morogoro Rural", "region": "Morogoro"},
  {"district": "Mvomero", "region": "Morogoro"},
  {"district": "Ulanga", "region": "Morogoro"},
  {"district": "Malinyi", "region": "Morogoro"},
  {"district": "Masasi Town", "region": "Mtwara"},
  {"district": "Masasi Rural", "region": "Mtwara"},
  {"district": "Mtwara Municipal", "region": "Mtwara"},
  {"district": "Mtwara Rural", "region": "Mtwara"},
  {"district": "Nanyumbu", "region": "Mtwara"},
  {"district": "Newala", "region": "Mtwara"},
  {"district": "Tandahimba", "region": "Mtwara"},
  {"district": "Ilemela", "region": "Mwanza"},
  {"district": "Kwimba", "region": "Mwanza"},
  {"district": "Magu", "region": "Mwanza"},
  {"district": "Misungwi", "region": "Mwanza"},
  {"district": "Nyamagana", "region": "Mwanza"},
  {"district": "Sengerema", "region": "Mwanza"},
  {"district": "Ukerewe", "region": "Mwanza"},
  {"district": "Ludewa", "region": "Njombe"},
  {"district": "Makambako Town", "region": "Njombe"},
  {"district": "Makete", "region": "Njombe"},
  {"district": "Njombe Town", "region": "Njombe"},
  {"district": "Njombe Rural", "region": "Njombe"},
  {"district": "Wanging'ombe", "region": "Njombe"},
  {"district": "Micheweni", "region": "Pemba North"},
  {"district": "Wete", "region": "Pemba North"},
  {"district": "Chake Chake", "region": "Pemba South"},
  {"district": "Mkoani", "region": "Pemba South"},
  {"district": "Bagamoyo", "region": "Pwani"},
  {"district": "Kibaha Town", "region": "Pwani"},
  {"district": "Kibaha Rural", "region": "Pwani"},
  {"district": "Kisarawe", "region": "Pwani"},
  {"district": "Mafia", "region": "Pwani"},
  {"district": "Mkuranga", "region": "Pwani"},
  {"district": "Rufiji", "region": "Pwani"},
  {"district": "Kalambo", "region": "Rukwa"},
  {"district": "Nkasi", "region": "Rukwa"},
  {"district": "Sumbawanga Municipal", "region": "Rukwa"},
  {"district": "Sumbawanga Rural", "region": "Rukwa"},
  {"district": "Mbinga", "region": "Ruvuma"},
  {"district": "Nyasa", "region": "Ruvuma"},
  {"district": "Songea Municipal", "region": "Ruvuma"},
  {"district": "Songea Rural", "region": "Ruvuma"},
  {"district": "Tunduru", "region": "Ruvuma"},
  {"district": "Igunga", "region": "Tabora"},
  {"district": "Kaliua", "region": "Tabora"},
  {"district": "Nzega Town", "region": "Tabora"},
  {"district": "Nzega Rural", "region": "Tabora"},
  {"district": "Sikonge", "region": "Tabora"},
  {"district": "Tabora Municipal", "region": "Tabora"},
  {"district": "Urambo", "region": "Tabora"},
  {"district": "Chunya", "region": "Mbeya"},
  {"district": "Kasulu", "region": "Kigoma"},
  {"district": "Singida", "region": "Singida"},
  {"district": "Siha", "region": "Kilimanjaro"}
];
